# --------------------------------------------------
# - Single configuration deployment YAML for MPI-Operator
# - Include:
#      CRD deployment
#      Namespace deployment
#      RBAC deployment
#      MPI-operator container deployment set
# --------------------------------------------------
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              mpiReplicaSpecs:
                properties:
                  Launcher:
                    properties:
                      replicas:
                        maximum: 1
                        minimum: 1
                        type: integer
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  Worker:
                    properties:
                      replicas:
                        minimum: 1
                        type: integer
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
              slotsPerWorker:
                minimum: 1
                type: integer
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              mpiReplicaSpecs:
                properties:
                  Launcher:
                    properties:
                      replicas:
                        maximum: 1
                        minimum: 1
                        type: integer
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  Worker:
                    properties:
                      replicas:
                        minimum: 1
                        type: integer
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
              slotsPerWorker:
                minimum: 1
                type: integer
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v2beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              mpiImplementation:
                enum:
                - OpenMPI
                - Intel
                type: string
              mpiReplicaSpecs:
                properties:
                  Launcher:
                    properties:
                      replicas:
                        maximum: 1
                        minimum: 1
                        type: integer
                      restartPolicy:
                        enum:
                        - Never
                        - OnFailure
                        type: string
                      template:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  Worker:
                    properties:
                      replicas:
                        minimum: 1
                        type: integer
                      restartPolicy:
                        enum:
                        - Never
                        - OnFailure
                        type: string
                      template:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                required:
                - Launcher
                type: object
              runPolicy:
                properties:
                  activeDeadlineSeconds:
                    description: |
                      Defines the duration in seconds, relative to its start time, that the launcher
                      Job may be active before the system tries to terminate it. Defaults to infinite.
                    minimum: 0
                    type: integer
                  backoffLimit:
                    description: Specifies the number of retries before marking the
                      launcher Job as failed. Defaults to 6.
                    minimum: 0
                    type: integer
                  cleanPodPolicy:
                    description: Defines which worker Pods must be deleted after the
                      Job completes
                    enum:
                    - None
                    - Running
                    - All
                    type: string
                  ttlSecondsAfterFinished:
                    description: |
                      Defines the TTL to clean up the launcher Job.
                      Defaults to infinite. Requires kubernetes 1.21+.
                    minimum: 0
                    type: integer
                type: object
              slotsPerWorker:
                minimum: 1
                type: integer
              sshAuthMountPath:
                type: string
            type: object
          status:
            properties:
              completionTime:
                format: date-time
                type: string
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    lastUpdateTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      enum:
                      - Created
                      - Running
                      - Restarting
                      - Succeeded
                      - Failed
                      type: string
                  type: object
                type: array
              lastReconcileTime:
                format: date-time
                type: string
              replicaStatuses:
                properties:
                  Launcher:
                    properties:
                      active:
                        type: integer
                      failed:
                        type: integer
                      succeeded:
                        type: integer
                    type: object
                  Worker:
                    properties:
                      active:
                        type: integer
                      failed:
                        type: integer
                      succeeded:
                        type: integer
                    type: object
                type: object
              startTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            slotsPerWorker:
              type: integer
              minimum: 1
            mpiReplicaSpecs:
              properties:
                Launcher:
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                      maximum: 1
                Worker:
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: mpi-operator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mpi-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - list
  - watch
# This is needed for the launcher Role.
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
# This is needed for the launcher Role.
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  - mpijobs/finalizers
  - mpijobs/status
  verbs:
  - "*"
- apiGroups:
  - scheduling.incubator.k8s.io
  - scheduling.sigs.dev
  resources:
  - queues
  - podgroups
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpi-operator
  namespace: mpi-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mpi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mpi-operator
subjects:
- kind: ServiceAccount
  name: mpi-operator
  namespace: mpi-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
  namespace: mpi-operator
  labels:
    app: mpi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-operator
  template:
    metadata:
      labels:
        app: mpi-operator
    spec:
      serviceAccountName: mpi-operator
      containers:
      - name: mpi-operator
        image: mpioperator/mpi-operator:latest
        command: ["/opt/mpi-operator.v1alpha2"]
        args: [
          "-alsologtostderr",
          "--kubectl-delivery-image",
          "mpioperator/kubectl-delivery:latest"
        ]
        imagePullPolicy: Always
